<a href="https://colab.research.google.com/github/Chandu0444/Machine_learning/blob/main/KNN_medical_MC(06_01_2025).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KNN (K-Nearest Neighbours)
it predicts a label for a new data point by looking at its neighbors.
STEPS

1. Pick a K value (K=number of neighbors)

2. For a new data point(called as query point), calculate its distance(Euclidean distance) from all other points in the dataset.

3. Find the K closest points(neighbors)

4. Classify on the basis of majority

In [2]:
# Dataset Link: https://drive.google.com/file/d/12-ZA7khoi7vJW7EKXvjYwqAdhcyvVG4H/view?usp=sharing

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data = pd.read_csv('/content/dataset.csv')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 692.0+ KB


In [6]:
data.shape

(4920, 18)

In [7]:
data

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                        NaN   
2      nodal_skin_eruptions    dischromic _patches                        NaN   
3                 skin_rash    dischromic _patches                        NaN   
4                 skin_rash   nodal_skin_eruptions                        NaN   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                       NaN                  NaN       NaN       NaN   
1                       NaN                  NaN       NaN       NaN   
2                       NaN                  NaN       NaN       NaN   
3                       NaN                  NaN       NaN       NaN   
4                       NaN                  NaN       NaN       NaN   
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness       NaN       NaN   
4916                    NaN                  NaN       NaN       NaN   
4917                    NaN                  NaN       NaN       NaN   
4918   small_dents_in_nails   inflammatory_nails       NaN       NaN   
4919      yellow_crust_ooze                  NaN       NaN       NaN   

     Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0          NaN        NaN        NaN        NaN        NaN        NaN   
1          NaN        NaN        NaN        NaN        NaN        NaN   
2          NaN        NaN        NaN        NaN        NaN        NaN   
3          NaN        NaN        NaN        NaN        NaN        NaN   
4          NaN        NaN        NaN        NaN        NaN        NaN   
...        ...        ...        ...        ...        ...        ...   
4915       NaN        NaN        NaN        NaN        NaN        NaN   
4916       NaN        NaN        NaN        NaN        NaN        NaN   
4917       NaN        NaN        NaN        NaN        NaN        NaN   
4918       NaN        NaN        NaN        NaN        NaN        NaN   
4919       NaN        NaN        NaN        NaN        NaN        NaN   

     Symptom_15 Symptom_16 Symptom_17  
0           NaN        NaN        NaN  
1           NaN        NaN        NaN  
2           NaN        NaN        NaN  
3           NaN        NaN        NaN  
4           NaN        NaN        NaN  
...         ...        ...        ...  
4915        NaN        NaN        NaN  
4916        NaN        NaN        NaN  
4917        NaN        NaN        NaN  
4918        NaN        NaN        NaN  
4919        NaN        NaN    

In [8]:
data.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [9]:
data.isnull().mean()*100

Disease        0.000000
Symptom_1      0.000000
Symptom_2      0.000000
Symptom_3      0.000000
Symptom_4      7.073171
Symptom_5     24.512195
Symptom_6     40.365854
Symptom_7     53.902439
Symptom_8     60.487805
Symptom_9     65.609756
Symptom_10    69.268293
Symptom_11    75.731707
Symptom_12    84.878049
Symptom_13    89.756098
Symptom_14    93.780488
Symptom_15    95.121951
Symptom_16    96.097561
Symptom_17    98.536585
dtype: float64

In [10]:
# removing columns which has mor than 50% of the null values
data_new = data[['Disease', 'Symptom_1','Symptom_2',	'Symptom_3', 'Symptom_4', 'Symptom_5', 'Symptom_6']]

In [11]:
data_new

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                        NaN   
2      nodal_skin_eruptions    dischromic _patches                        NaN   
3                 skin_rash    dischromic _patches                        NaN   
4                 skin_rash   nodal_skin_eruptions                        NaN   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6  
0                       NaN                  NaN  
1                       NaN                  NaN  
2                       NaN                  NaN  
3                       NaN                  NaN  
4                       NaN                  NaN  
...                     ...                  ...  
4915        loss_of_balance         unsteadiness  
4916                    NaN                  NaN  
4917                    NaN                  NaN  
4918   small_dents_in_nails   inflammatory_nails  
4919      yellow_crust_ooze                  NaN  

[4920 rows x 7 columns]

In [12]:
for col in data_new.columns:
  if data_new[col].dtype=='object':
    data_new[col] = data_new[col].fillna(data_new[col].mode()[0])
  else:
    data_new[col] = data_new[col].fillna(data_new[col].mean())

/tmp/ipython-input-288486247.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_new[col] = data_new[col].fillna(data_new[col].mode()[0])


In [13]:
data_new['Disease'].mode()[1]

'AIDS'

In [14]:
data_new.isnull().sum()

Disease      0
Symptom_1    0
Symptom_2    0
Symptom_3    0
Symptom_4    0
Symptom_5    0
Symptom_6    0
dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()
for col in data_new.columns:
    data_new[col] = le.fit_transform(data_new[col])

    for idx, cls in enumerate(le.classes_):
      print(f"{cls}->{idx}")


(vertigo) Paroymsal  Positional Vertigo->0
AIDS->1
Acne->2
Alcoholic hepatitis->3
Allergy->4
Arthritis->5
Bronchial Asthma->6
Cervical spondylosis->7
Chicken pox->8
Chronic cholestasis->9
Common Cold->10
Dengue->11
Diabetes ->12
Dimorphic hemmorhoids(piles)->13
Drug Reaction->14
Fungal infection->15
GERD->16
Gastroenteritis->17
Heart attack->18
Hepatitis B->19
Hepatitis C->20
Hepatitis D->21
Hepatitis E->22
Hypertension ->23
Hyperthyroidism->24
Hypoglycemia->25
Hypothyroidism->26
Impetigo->27
Jaundice->28
Malaria->29
Migraine->30
Osteoarthristis->31
Paralysis (brain hemorrhage)->32
Peptic ulcer diseae->33
Pneumonia->34
Psoriasis->35
Tuberculosis->36
Typhoid->37
Urinary tract infection->38
Varicose veins->39
hepatitis A->40
 acidity->0
 back_pain->1
 bladder_discomfort->2
 breathlessness->3
 burning_micturition->4
 chest_pain->5
 chills->6
 constipation->7
 continuous_sneezing->8
 cough->9
 cramps->10
 fatigue->11
 headache->12
 high_fever->13
 indigestion->14
 joint_pain->15
 mood_swin

/tmp/ipython-input-3552025304.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_new[col] = le.fit_transform(data_new[col])
/tmp/ipython-input-3552025304.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_new[col] = le.fit_transform(data_new[col])
/tmp/ipython-input-3552025304.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pan

# In KNN we do not remove duplicates, because the duplicates strengthens the classification

In [17]:
data_new['Disease'].values

array([15, 15, 15, ..., 38, 35, 27])

#Clustering Algo

In [18]:
x=data_new.drop('Disease',axis=1)
y=data_new['Disease']

In [19]:
y.unique()

array([15,  4, 16,  9, 14, 33,  1, 12, 17,  6, 23, 30,  7, 32, 28, 29,  8,
       11, 37, 40, 19, 20, 21, 22,  3, 36, 10, 34, 13, 18, 39, 26, 24, 25,
       31,  5,  0,  2, 38, 35, 27])

In [20]:
y.nunique()

41

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.20, random_state=52)

In [22]:
x_train.shape

(3936, 6)

In [23]:
y_train.shape

(3936,)

In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [25]:
y_pred = knn.predict(x_test)

In [26]:
from sklearn.metrics import *
acc=accuracy_score(y_test,y_pred)*100
acc

98.6788617886179

 What is .score?

 In machine learning, .score is a method in libraries like scikit-learn that returns a quantitative metric evaluating how well a trained model fits the data.

In [27]:
acc2 = knn.score(x_train,y_train)
acc2

0.9972052845528455

# predicting the new records

creating a new record

In [28]:
new_rec = pd.DataFrame(columns=x.columns)
new_rec

Empty DataFrame
Columns: [Symptom_1, Symptom_2, Symptom_3, Symptom_4, Symptom_5, Symptom_6]
Index: []

In [29]:
# adding cols in new_rec

new_rec.loc[0] = [23,56,34,89,23,72] # stores these values at index 0
new_rec.loc[3] = [65,32,4,33,12,21]  # stores these values at index 3
new_rec

Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6
0         23         56         34         89         23         72
3         65         32          4         33         12         21

In [30]:
knn.predict(new_rec)

array([28, 14])

#creating new Data frame to check the values of the classes

In [40]:
dis=pd.DataFrame(data['Disease'].sort_values().unique())
dis.head()

0
0  (vertigo) Paroymsal  Positional Vertigo
1                                     AIDS
2                                     Acne
3                      Alcoholic hepatitis
4                                  Allergy

In [38]:
dis.loc[28]

0    Jaundice
Name: 28, dtype: object