<a href="https://colab.research.google.com/github/Chandu0444/Machine_learning/blob/main/LDA_HANDSON_MC(24_10_25).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#LDA

In [ ]:
import pandas as pd
df = pd.DataFrame({"Gender":["Male","Male","Male","Male","Male","Male","Female","Female","Female","Female","Female","Female"],
                   "Shoe_Size":[9,8,8.5,10,7,9.5,7,6,6.5,5,8,7.5],
                   "Height":[6.1,5.7,5.4,5.8,6.2,5.6,5.5,5.1,5.2,5,4.11,5.9]})
df


Gender  Shoe_Size  Height
0     Male        9.0    6.10
1     Male        8.0    5.70
2     Male        8.5    5.40
3     Male       10.0    5.80
4     Male        7.0    6.20
5     Male        9.5    5.60
6   Female        7.0    5.50
7   Female        6.0    5.10
8   Female        6.5    5.20
9   Female        5.0    5.00
10  Female        8.0    4.11
11  Female        7.5    5.90

In [ ]:
df_male=df[df['Gender']=='Male']
df_female=df[df['Gender']=='Female']

In [ ]:
m_array = df_male[["Shoe_Size","Height"]].to_numpy().transpose()
f_array = df_female[["Shoe_Size","Height"]].to_numpy().transpose()

In [ ]:
import numpy as np
Cov_male = np.cov(m_array)
Cov_male

array([[ 1.16666667, -0.12      ],
       [-0.12      ,  0.092     ]])

In [ ]:
Cov_female = np.cov(f_array)
Cov_female

array([[ 1.16666667, -0.074     ],
       [-0.074     ,  0.35855   ]])

In [ ]:
w= (Cov_male + Cov_female)/2
w

array([[ 1.16666667, -0.097     ],
       [-0.097     ,  0.225275  ]])

Find inverse for W

In [ ]:
w_inv=np.linalg.inv(w)
w_inv

array([[0.88896796, 0.38277613],
       [0.38277613, 4.60383657]])

In [ ]:
total_array=df[["Shoe_Size","Height"]].to_numpy().transpose()

In [ ]:
cov_t=np.cov(total_array)
cov_t

array([[2.15151515, 0.27454545],
       [0.27454545, 0.32540227]])

In [ ]:
B = cov_t-w
B

array([[0.98484848, 0.37154545],
       [0.37154545, 0.10012727]])

In [ ]:
# step1: find the seperation matrix

S=np.dot(w_inv,B)
S

array([[1.01771748, 0.36861833],
       [2.08751104, 0.60318833]])

In [ ]:
# Step-2
# Find the eigen Value and Eigen Vector for S matrix

eig_vals =np.linalg.eig(S)
eig_vals

EigResult(eigenvalues=array([ 1.7118149 , -0.09090909]), eigenvectors=array([[ 0.46903523, -0.31551599],
       [ 0.88317946,  0.94892026]]))

In [ ]:
# Step-3
# Sort the eigen value from higher to lower, find the eigen vector corresponding to highest eigen value
e = np.array([0.4690,0.8831]) #--> eigen vector corresponding to eigen value 1.711

In [ ]:
# step4: finding linear discriminent
total_array

array([[ 9.  ,  8.  ,  8.5 , 10.  ,  7.  ,  9.5 ,  7.  ,  6.  ,  6.5 ,
         5.  ,  8.  ,  7.5 ],
       [ 6.1 ,  5.7 ,  5.4 ,  5.8 ,  6.2 ,  5.6 ,  5.5 ,  5.1 ,  5.2 ,
         5.  ,  4.11,  5.9 ]])

In [ ]:
discrimnent=np.dot(e,total_array)

In [ ]:
df['descrimenent']=np.dot(e,total_array)
df

Gender  Shoe_Size  Height  descrimenent
0     Male        9.0    6.10      9.607910
1     Male        8.0    5.70      8.785670
2     Male        8.5    5.40      8.755240
3     Male       10.0    5.80      9.811980
4     Male        7.0    6.20      8.758220
5     Male        9.5    5.60      9.400860
6   Female        7.0    5.50      8.140050
7   Female        6.0    5.10      7.317810
8   Female        6.5    5.20      7.640620
9   Female        5.0    5.00      6.760500
10  Female        8.0    4.11      7.381541
11  Female        7.5    5.90      8.727790

#PCA

In [ ]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler

In [ ]:
data=load_wine()

In [ ]:
data

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [ ]:
x=data['data']
scalar=StandardScaler()
x_standrdzed=scalar.fit_transform(x)

In [ ]:
y=data['target']

In [ ]:
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
pca= PCA(n_components=2)
lda=LinearDiscriminantAnalysis(n_components=2)


In [ ]:
x_reduced_byPCA=pca.fit_transform(x_standrdzed)
x_reduced_byLDA=lda.fit_transform(x_standrdzed,y) # for lda we should give both x and y

#Classifier using PCA reduced dim

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

In [ ]:
x_train, x_test, y_train, y_test= train_test_split(x_reduced_byPCA,y,test_size=0.3)
log1=LogisticRegression()
log_model1=log1.fit(x_train,y_train)
y_test_pred=log_model1.predict(x_test)
print(confusion_matrix(y_test_pred,y_test))


[[16  3  0]
 [ 0 22  0]
 [ 0  1 12]]


#classifier using LDA reduced dim

In [ ]:
x_train_lda, x_test_lda, y_train_lda , y_test_lda =  train_test_split(x_reduced_byLDA,y, test_size=0.3)
log2=LogisticRegression()
log_model2=log2.fit(x_train,y_train)
y_test_pred1=log_model2.predict(x_test)
print(confusion_matrix(y_test_pred1,y_test))

[[16  3  0]
 [ 0 22  0]
 [ 0  1 12]]
