<a href="https://colab.research.google.com/github/Chandu0444/Machine_learning/blob/main/PCA_handson_MC(04_01_2025).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PCA handson with digits dataset.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn import datasets

In [ ]:
data=datasets.load_digits()

In [ ]:
data

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

#splitting the dataset as x,y variables

In [ ]:
x=data['data']
y=data['target']

In [ ]:
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [ ]:
data['target_names']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.shape

(1797, 64)

In [ ]:
y.shape

(1797,)

Standardise the data.(all values get closer the mean)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
se=StandardScaler()
x_std=se.fit_transform(x)
x_std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [ ]:
x_std.shape     #64 feature

(1797, 64)

Implementing the pca for dimensionality(features) reduction.

we have 64 columns

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca=PCA(n_components=0.80)
x_pca=pca.fit_transform(x_std)
print(f"No.of rows and cols after implementing the the pca: {x_pca.shape}")
x_pca

No.of rows and cols after implementing the the pca: (1797, 21)


array([[-1.91421366, -0.95450157, -3.94603482, ...,  0.41275404,
         0.43051695,  0.45099368],
       [-0.58898033,  0.9246358 ,  3.92475494, ...,  0.55308473,
        -0.06967631,  0.90981832],
       [-1.30203906, -0.31718883,  3.02333293, ..., -1.06555601,
        -1.13345406, -0.52591658],
       ...,
       [-1.02259599, -0.14791087,  2.46997365, ..., -1.61210006,
         0.18230257,  0.16666651],
       [-1.07605522, -0.38090625, -2.45548693, ..., -1.76918064,
         0.77471846, -0.13566828],
       [ 1.25770233, -2.22759088,  0.28362789, ..., -2.43897852,
        -1.13276155, -1.11458695]])

Using pca we reduced 64 columns **to** 21 columns

Models that are suitable for classification - log reg, decion tree, random forest.


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#log reg
le=LogisticRegression()
x_train_pca, x_test_pca, y_train, y_test=train_test_split(x_pca,y,test_size=0.2)
model_fit1=le.fit(x_pca,y)
y_test_pred1=model_fit1.predict(x_test_pca)
accuracy_score(y_test,y_test_pred1)*100

96.94444444444444

In [ ]:
#decision tree
from sklearn.tree import DecisionTreeClassifier
de=DecisionTreeClassifier()
model_fit2=de.fit(x_train_pca,y_train)
y_test_pred2=model_fit2.predict(x_test_pca)
accuracy_score(y_test,y_test_pred2)*100

85.0

In [ ]:
#random forest
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
model_fit3=rf.fit(x_train_pca,y_train)
y_test_pred3=model_fit3.predict(x_test_pca)
accuracy_score(y_test_pred3,y_test)*100

95.27777777777777